/*
 * generated by Xtext
 */
package org.sqlproc.meta;

import org.eclipse.xtext.resource.IResourceFactory;
import org.sqlproc.meta.generator.IGenerator2;
import org.sqlproc.meta.generator.ProcessorMetaGenerator2;
import org.sqlproc.meta.property.ModelProperty;
import org.sqlproc.meta.property.ModelPropertyBean;
import org.sqlproc.meta.resolver.DbResolver;
import org.sqlproc.meta.resolver.DbResolverBean;
import org.sqlproc.meta.resolver.PojoResolverFactory;
import org.sqlproc.meta.resolver.PojoResolverFactoryBean;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProcessorMetaRuntimeModule extends org.sqlproc.meta.AbstractProcessorMetaRuntimeModule {

    public Class<? extends ModelProperty> bindModelProperty() {
        return ModelPropertyBean.class;
    }

    @Override
    public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return ProcessorNameProvider.class;
    }

    public Class<? extends PojoResolverFactory> bindPojoResolverFactory() {
        return PojoResolverFactoryBean.class;
    }

    public Class<? extends DbResolver> bindDbResolver() {
        return DbResolverBean.class;
    }

    @Override
    public Class<? extends IResourceFactory> bindIResourceFactory() {
        return ProcessorResourceFactory.class;
    }

    public Class<? extends IGenerator2> bindIGenerator2() {
        return ProcessorMetaGenerator2.class;
    }
}
